# Generated by Django 5.1.3 on 2024-11-15 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='especialidad',
            field=models.CharField(blank=True, choices=[('cardiologia', 'Cardiología'), ('dermatologia', 'Dermatología'), ('pediatria', 'Pediatría')], max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
